name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/azureuser/penugasan1-netics  # ganti path sesuai tempat kamu clone repo-nya di VM
            git pull origin main
            sudo apt-get install -y nodejs
            npm install
            sudo npm install -g pm2
            mkdir -p /home/azureuser/penugasan1-netics
            cd /home/azureuser/penugasan1-netics
            if [ ! -d ".git" ]; then
              git clone git@github.com:hihanghoeng33/penugasan1-netics.git
            else
              git pull origin main
            fi
            pm2 restart netics || pm2 start index.js --name netics
          EOF
