name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts


      - name: Deploy via SSH
        run: |
           ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
              cd /home/azureuser/penugasan1-netics || git clone git@github.com:hihanghoeng33/penugasan1-netics.git /home/azureuser/penugasan1-netics && cd /home/azureuser/penugasan1-netics
              git pull origin main
              npm install
              pm2 restart netics || pm2 start index.js --name netics
            EOF
